# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, verbose_name='sex')),
                ('telphone', models.CharField(max_length=20, verbose_name='telephone')),
                ('mobile', models.CharField(max_length=11, verbose_name='cellphone')),
            ],
        ),
    ]
