# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='mobile',
        ),
        migrations.AddField(
            model_name='address',
            name='notes',
            field=models.CharField(default='--', max_length=50, verbose_name='notes'),
        ),
    ]
