# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20180706_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='firstname',
            field=models.CharField(default='', max_length=40, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='address',
            name='lastname',
            field=models.CharField(default='', max_length=40, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='address',
            name='notes',
            field=models.CharField(default='', max_length=50, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='address',
            name='telphone',
            field=models.CharField(max_length=20, unique=True, verbose_name='telephone'),
        ),
    ]
