# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20180706_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default='', max_length=40, verbose_name='email'),
        ),
    ]
